[phases.setup]
# Herramientas y extensiones necesarias en build
packages = [
  "php",
  "composer",
  "nodejs",
  "npm",
  "php-extensions.intl",
  "php-extensions.zip"
]

[phases.install]
cmds = [
  # Dependencias PHP (sin dev) y Node
  "composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction",
  "npm ci || npm install"
]

[phases.build]
cmds = [
  # Compila assets y prepara caches de Laravel
  "php artisan filament:assets --no-interaction || true",
  "npm run build",
  "php artisan storage:link || true",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
# Ejecuta migraciones y arranca Apache (Heroku PHP) sirviendo /public
cmd = "php artisan migrate --force && vendor/bin/heroku-php-apache2 public/"